/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GpgEncryptPlugin
});
module.exports = __toCommonJS(main_exports);

// src/gpg.ts
var import_child_process = require("child_process");
var globalArgs = ["--batch"];
function AditionalArgs(settings) {
  let aditionalArgs = [];
  if (settings.pgpAlwaysTrust) {
    aditionalArgs = aditionalArgs.concat(["--trust-model", "always"]);
  }
  return aditionalArgs;
}
function spawnGPG(settings, input, args) {
  return new Promise((resolve) => {
    try {
      if (!args) {
        args = [];
      }
      let fullArgs = globalArgs.concat(args);
      const buffers = [];
      let buffersLength = 0;
      let error = "";
      let command = "";
      if (settings.pgpAditionalCommands && settings.pgpAditionalCommandsBefore !== "") {
        command = settings.pgpAditionalCommandsBefore + " && ";
      }
      command += '"' + settings.pgpExecPath + '"';
      fullArgs.forEach((arg) => {
        command += " " + arg;
      });
      if (settings.pgpAditionalCommands && settings.pgpAditionalCommandsAfter !== "") {
        command += " && " + settings.pgpAditionalCommandsAfter;
      }
      if (settings.pgpAditionalCommandsConsole) {
        console.log(command);
      }
      const gpg = (0, import_child_process.spawn)(command, { shell: true });
      gpg.stdout.on("data", (buf) => {
        buffers.push(buf);
        buffersLength += buf.length;
      });
      gpg.stderr.on("data", (buf) => {
        error += buf.toString("utf8");
      });
      gpg.on("close", (code) => {
        const msg = Buffer.concat(buffers, buffersLength);
        if (code !== 0) {
          resolve({
            result: void 0,
            error: new Error(error || msg.toString())
          });
        }
        resolve({
          result: msg,
          error: error.length > 0 ? new Error(error) : void 0
        });
      });
      gpg.on("error", (err) => {
        if (settings.pgpAditionalCommandsConsole) {
          console.error(err);
        }
        resolve({
          result: void 0,
          error: err
        });
      });
      if (input) {
        gpg.stdin.end(input);
      }
    } catch (ex) {
      resolve({
        result: void 0,
        error: ex
      });
    }
  });
}
async function getListPublicKey(settings) {
  const gpgResult = await spawnGPG(settings, null, ["--logger-fd", "1", "--list-public-keys", "--with-colons"]);
  if (!gpgResult.result) {
    return [];
  }
  const lines = gpgResult.result.toString().trim().split("\n");
  const keys = [];
  let currentKeyID = null;
  for (const line of lines) {
    const parts = line.split(":");
    if (parts[0] === "pub") {
      currentKeyID = parts[4];
    }
    if (parts[0] === "uid" && currentKeyID) {
      keys.push({
        keyID: currentKeyID,
        userID: parts[9]
      });
    }
  }
  return keys;
}
async function gpgEncrypt(settings, plainText, publicKeyIds, signPublicKeyId) {
  if (publicKeyIds.length <= 0) {
    return {
      result: void 0,
      error: new Error("\u274C Select at least one key")
    };
  }
  let args = ["--encrypt", "--armor"].concat(AditionalArgs(settings));
  if (signPublicKeyId != "0") {
    args = args.concat(["--sign", "--local-user", signPublicKeyId]);
  }
  publicKeyIds.forEach((publicKey) => {
    args = args.concat(["--recipient", publicKey]);
  });
  const gpgResult = await spawnGPG(settings, plainText, args);
  if (gpgResult.error) {
    return gpgResult;
  }
  if (!gpgResult.result) {
    return {
      result: void 0,
      error: new Error("\u274C Encrypt failed, result is empty")
    };
  }
  return {
    result: gpgResult.result,
    error: void 0
  };
}
async function gpgDecrypt(settings, encryptedText) {
  let args = ["--decrypt"].concat(AditionalArgs(settings));
  const gpgResult = await spawnGPG(settings, encryptedText, args);
  if (gpgResult.error) {
    return gpgResult;
  }
  if (!gpgResult.result) {
    return {
      result: void 0,
      error: new Error("\u274C Decrypt failed, result is empty")
    };
  }
  return {
    result: gpgResult.result,
    error: void 0
  };
}

// src/SettingsTab.ts
var import_obsidian = require("obsidian");

// src/Settings.ts
var DEFAULT_SETTINGS = {
  pgpExecPath: getDefaultExecPath(),
  pgpSignPublicKeyId: "0",
  pgpAlwaysTrust: false,
  pgpDefaultEncryptKeys: [],
  pgpLibrary: "openpgpjs",
  pgpAditionalCommands: false,
  pgpAditionalCommandsBefore: "",
  pgpAditionalCommandsAfter: "",
  pgpAditionalCommandsConsole: false
};
var Settings = class {
  // Constructor of modal encrypt
  constructor(plugin) {
    this.plugin = plugin;
  }
  // Load Settings from Plugin Data
  async loadSettings() {
    this.plugin.settings = Object.assign({}, DEFAULT_SETTINGS, await this.plugin.loadData());
  }
  // Save Settings to Plugin Data
  async saveSettings() {
    await this.plugin.saveData(this.plugin.settings);
  }
};
function getDefaultExecPath() {
  switch (process.platform) {
    // In case of Windows OS
    case "win32":
      return "C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe";
    // In case of MacOS
    case "darwin":
      return "/usr/local/bin/gpg";
    // In case of Linux
    case "linux":
      return "/usr/bin/gpg";
    // In default value return empty
    default:
      return "";
  }
}

// src/SettingsTab.ts
var fs = require("fs");
var GpgSettingsTab = class extends import_obsidian.PluginSettingTab {
  // Constructor with App and GpgEncryptPlugin
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  // Display function in settings tabs
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.gpgLibrary = new import_obsidian.Setting(containerEl).setName("GPG Library").setDesc("Select which GPG library you want to use (Tip: If you want the app to work on mobile devices, use openpgpjs)").addDropdown((dropdown) => {
      dropdown.addOption("openpgpjs", "openpgpjs");
      dropdown.addOption("cli", "CLI commands");
      dropdown.setValue(this.plugin.settings.pgpLibrary);
      dropdown.onChange((value) => {
        this.plugin.settings.pgpLibrary = value;
        this.RefreshLibrary(value);
      });
    });
    this.gpgExecPath = new import_obsidian.Setting(containerEl).setName("GPG executable").setDesc("Path to GPG executable").addText((text) => text.setPlaceholder("gpg").setValue(this.plugin.settings.pgpExecPath).onChange(async (value) => {
      await this.checkGpgPath(value);
    }));
    this.gpgExecPathStatus = this.gpgExecPath.descEl.createDiv();
    this.gpgPublicKeysList = new import_obsidian.Setting(containerEl).setName("Public keys");
    this.checkGpgPath(this.plugin.settings.pgpExecPath);
    this.gpgAlwaysTrust = new import_obsidian.Setting(containerEl).setName("Always trust any key").setDesc("Always trust any used GPG key").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.pgpAlwaysTrust);
      toggle.onChange(async (value) => {
        this.plugin.settings.pgpAlwaysTrust = value;
        await new Settings(this.plugin).saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Sign encrypted text").setDesc("Sign the encrypted text with GPG").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.pgpSignPublicKeyId != "0");
      toggle.onChange((value) => {
        this.RefreshListSign(value);
      });
    });
    this.gpgSignKeyId = new import_obsidian.Setting(containerEl);
    this.RefreshListSign(this.plugin.settings.pgpSignPublicKeyId != "0");
    this.gpgAditionalCommands = new import_obsidian.Setting(containerEl).setName("Aditional commands").setDesc("Add custom commands to be executed before or after the gpg command calls").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.pgpAditionalCommands);
      toggle.onChange((value) => {
        this.RefreshAditionalCommands(value);
      });
    });
    this.gpgAditionalCommandsWarning = this.gpgAditionalCommands.descEl.createDiv();
    this.gpgAditionalCommandsWarning.setText("Warning: Only advance users");
    this.gpgAditionalCommandsWarning.className = "text-color-red";
    this.gpgAditionalCommandsBefore = new import_obsidian.Setting(containerEl);
    this.gpgAditionalCommandsAfter = new import_obsidian.Setting(containerEl);
    this.gpgAditionalCommandsConsole = new import_obsidian.Setting(containerEl);
    this.RefreshLibrary(this.plugin.settings.pgpLibrary);
    this.RefreshAditionalCommands(this.plugin.settings.pgpAditionalCommands);
  }
  // Function to check if GPG Path exits
  async checkGpgPath(value) {
    if (this.plugin.settings.pgpLibrary == "openpgpjs")
      return;
    this.plugin.settings.pgpExecPath = value;
    await new Settings(this.plugin).saveSettings();
    this.gpgPublicKeysList.settingEl.hide();
    this.changeGpgPathStatus("Loading..." /* LOADING */);
    try {
      if (!fs.existsSync(value)) {
        this.changeGpgPathStatus("File or directory not found" /* FILE_NOT_FOUND */);
        return;
      }
      if (!value.endsWith("gpg") && !value.endsWith("gpg.exe") && !value.endsWith("gpg2") && !value.endsWith("gpg2.exe")) {
        this.changeGpgPathStatus("GPG is not in this path" /* NO_GPG_IN_PATH */);
        return;
      }
      let gpgResult = await spawnGPG(this.plugin.settings, null, ["--logger-fd", "1", "--version"]);
      if (gpgResult.result && !gpgResult.error) {
        let version = gpgResult.result.toString().trim();
        if (version.includes("gpg") && version.includes("GnuPG")) {
          this.changeGpgPathStatus("Ok" /* OK */);
          await this.RefreshGpgPublicKeyList();
          return;
        } else {
          this.changeGpgPathStatus("The output does not indicate this is GPG" /* NO_GPG_IN_OUTPUT */);
          return;
        }
      } else {
        this.changeGpgPathStatus("An unknown error occurred" /* UNKNOWN_ERROR */);
        throw gpgResult.error;
      }
    } catch (ex) {
      switch (ex.code) {
        // In case or ENOENT
        case "ENOENT":
          this.changeGpgPathStatus("File or directory not found" /* FILE_NOT_FOUND */);
          break;
        // In case or EACCES or EPERM
        case "EACCES":
        case "EPERM":
          this.changeGpgPathStatus("Access to the executable file has been denied" /* NOT_PERMISSION */);
          break;
        // In another error code
        default:
          this.changeGpgPathStatus("An unknown error occurred" /* UNKNOWN_ERROR */);
          break;
      }
      throw ex;
    }
  }
  // Function to change GPG executable path status
  changeGpgPathStatus(status) {
    this.gpgExecPathStatus.setText(`Status: ${status}`);
    switch (status) {
      // In case of Loading status
      case "Loading..." /* LOADING */:
        this.gpgExecPathStatus.className = "text-color-orange";
        break;
      // In case of OK status
      case "Ok" /* OK */:
        this.gpgExecPathStatus.className = "text-color-green";
        break;
      // In case of error status
      default:
        this.gpgExecPathStatus.className = "text-color-red";
        break;
    }
  }
  // Function to refresh list of GPG Public Keys
  async RefreshGpgPublicKeyList() {
    let gpgPublicKeys = await getListPublicKey(this.plugin.settings);
    while (this.gpgPublicKeysList.descEl.firstChild) {
      this.gpgPublicKeysList.descEl.removeChild(this.gpgPublicKeysList.descEl.firstChild);
    }
    this.gpgPublicKeysList.setDesc("List of GPG public keys (Mark the keys that by default will be used for encryption).");
    this.gpgPublicKeysList.descEl.createDiv().className = "div-spacer";
    gpgPublicKeys.forEach((gpgPublicKey) => {
      let div = this.gpgPublicKeysList.descEl.createDiv();
      let item = new import_obsidian.Setting(div);
      item.setName(gpgPublicKey.keyID);
      item.setDesc(gpgPublicKey.userID);
      item.addToggle((toggle) => {
        toggle.setValue(this.plugin.settings.pgpDefaultEncryptKeys.indexOf(gpgPublicKey.keyID) > -1);
        toggle.onChange(async (value) => {
          if (value && this.plugin.settings.pgpDefaultEncryptKeys.indexOf(gpgPublicKey.keyID) == -1) {
            this.plugin.settings.pgpDefaultEncryptKeys.push(gpgPublicKey.keyID);
          } else if (!value && this.plugin.settings.pgpDefaultEncryptKeys.indexOf(gpgPublicKey.keyID) > -1) {
            this.plugin.settings.pgpDefaultEncryptKeys.remove(gpgPublicKey.keyID);
          }
          await new Settings(this.plugin).saveSettings();
        });
      });
    });
    this.gpgPublicKeysList.settingEl.show();
  }
  // Function to refresh List of Sign Keys ID
  async RefreshListSign(requireSign) {
    this.gpgSignKeyId.clear();
    this.gpgSignKeyId.setName("GPG key to sign");
    this.gpgSignKeyId.setDesc("GPG key to sign the encrypted text");
    requireSign ? this.gpgSignKeyId.settingEl.show() : this.gpgSignKeyId.settingEl.hide();
    if (requireSign) {
      let gpgPublicKeys = await getListPublicKey(this.plugin.settings);
      this.gpgSignKeyId.addDropdown((dropDown) => {
        dropDown.addOption("0", "Select a key to sign");
        gpgPublicKeys.forEach((gpgPublicKey) => {
          dropDown.addOption(gpgPublicKey.keyID, "(" + gpgPublicKey.keyID + ") " + gpgPublicKey.userID);
        });
        dropDown.onChange(async (value) => {
          this.plugin.settings.pgpSignPublicKeyId = value;
          await new Settings(this.plugin).saveSettings();
        });
        dropDown.setValue(this.plugin.settings.pgpSignPublicKeyId);
      });
    } else {
      this.plugin.settings.pgpSignPublicKeyId = "0";
      await new Settings(this.plugin).saveSettings();
    }
  }
  // Function to refresh List of Sign Keys ID
  async RefreshAditionalCommands(aditionalCommands) {
    this.gpgAditionalCommandsBefore.clear();
    this.gpgAditionalCommandsAfter.clear();
    this.gpgAditionalCommandsConsole.clear();
    this.gpgAditionalCommandsBefore.setName("Additional Commands (Before)");
    this.gpgAditionalCommandsAfter.setName("Additional Commands (After)");
    this.gpgAditionalCommandsConsole.setName("Print command in Obsidian Developer Console");
    this.gpgAditionalCommandsBefore.setDesc("Enter the commands to be executed before running the gpg commands (Note: If you need to nest more than one command use &&, DO NOT include closing characters && as these will be added automatically)");
    this.gpgAditionalCommandsAfter.setDesc("Enter the commands to be executed after running the gpg commands (Note: If you need to nest more than one command use &&, DO NOT include closing characters && as these will be added automatically)");
    this.gpgAditionalCommandsConsole.setDesc("Print whole command in the Obsidian Developer Console to debug (cmd+option+i Mac - ctrl+shift+i Windows)");
    aditionalCommands ? this.gpgAditionalCommandsBefore.settingEl.show() : this.gpgAditionalCommandsBefore.settingEl.hide();
    aditionalCommands ? this.gpgAditionalCommandsAfter.settingEl.show() : this.gpgAditionalCommandsAfter.settingEl.hide();
    aditionalCommands ? this.gpgAditionalCommandsConsole.settingEl.show() : this.gpgAditionalCommandsConsole.settingEl.hide();
    this.gpgAditionalCommandsBefore.addText((text) => text.setPlaceholder("command").setValue(this.plugin.settings.pgpAditionalCommandsBefore).onChange(async (value) => {
      this.plugin.settings.pgpAditionalCommandsBefore = value;
      await new Settings(this.plugin).saveSettings();
      await this.checkGpgPath(this.plugin.settings.pgpExecPath);
    }));
    this.gpgAditionalCommandsAfter.addText((text) => text.setPlaceholder("command").setValue(this.plugin.settings.pgpAditionalCommandsAfter).onChange(async (value) => {
      this.plugin.settings.pgpAditionalCommandsAfter = value;
      await new Settings(this.plugin).saveSettings();
      await this.checkGpgPath(this.plugin.settings.pgpExecPath);
    }));
    this.gpgAditionalCommandsConsole.addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.pgpAditionalCommandsConsole);
      toggle.onChange(async (value) => {
        this.plugin.settings.pgpAditionalCommandsConsole = value;
        await new Settings(this.plugin).saveSettings();
      });
    });
    this.plugin.settings.pgpAditionalCommands = aditionalCommands;
    await new Settings(this.plugin).saveSettings();
  }
  // Function to refresh pgp library
  RefreshLibrary(value) {
    if (value == "openpgpjs") {
      this.plugin.settings.pgpAditionalCommands = false;
      this.gpgAditionalCommands.settingEl.hide();
      this.gpgExecPath.settingEl.hide();
      this.gpgPublicKeysList.settingEl.hide();
      this.gpgSignKeyId.settingEl.hide();
      this.gpgAlwaysTrust.settingEl.hide();
    } else {
      this.gpgAditionalCommands.settingEl.show();
      this.gpgExecPath.settingEl.show();
      this.gpgPublicKeysList.settingEl.show();
      this.gpgAlwaysTrust.settingEl.show();
      if (this.plugin.settings.pgpSignPublicKeyId != "0")
        this.gpgSignKeyId.settingEl.show();
      this.checkGpgPath(this.plugin.settings.pgpExecPath);
    }
    this.RefreshAditionalCommands(this.plugin.settings.pgpAditionalCommands);
  }
};

// src/EncryptModal.ts
var import_obsidian2 = require("obsidian");
var GPG_INLINE_ENCRYPT_PREFIX = "gpg-base-64";
var EncryptModal = class extends import_obsidian2.Modal {
  // Constructor of modal encrypt
  constructor(app, plugin, mode, editor, view) {
    super(app);
    this.plugin = plugin;
    this.encryptMode = mode;
    this.editor = editor;
    this.view = view;
    this.listPublicKeyToEncrypt = [];
  }
  // OnOpen Method
  async onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "Encrypt " + this.encryptMode });
    if (this.encryptMode == "Inline" /* INLINE */ && !this.editor.somethingSelected()) {
      new import_obsidian2.Notice("\u274C Select some text to encrypt");
      this.close();
    }
    if (this.encryptMode == "Document" /* DOCUMENT */ && !this.editor) {
      new import_obsidian2.Notice("\u274C Open a file to encrypt");
      this.close();
    }
    contentEl.createEl("p", { text: "Select which Public GPG key(s) you want to be able to decrypt the text:" });
    let gpgPublicKeys = await getListPublicKey(this.plugin.settings);
    let gpgSignName = "";
    gpgPublicKeys.forEach((gpgPublicKey) => {
      new import_obsidian2.Setting(contentEl).setName("(" + gpgPublicKey.keyID + ") " + gpgPublicKey.userID).addToggle((toggle) => {
        let defaultValue = this.plugin.settings.pgpDefaultEncryptKeys.indexOf(gpgPublicKey.keyID) > -1;
        toggle.setValue(defaultValue);
        this.toogleOnChange(defaultValue, gpgPublicKey.keyID);
        toggle.onChange((value) => {
          this.toogleOnChange(value, gpgPublicKey.keyID);
        });
      });
      if (gpgPublicKey.keyID == this.plugin.settings.pgpSignPublicKeyId) {
        gpgSignName = gpgPublicKey.userID;
      }
    });
    let signNote = this.plugin.settings.pgpSignPublicKeyId == "0" ? "" : "Note: Remember that this text will be encrypted and SIGNED with the key (" + this.plugin.settings.pgpSignPublicKeyId + ") " + gpgSignName;
    let buttonName = this.plugin.settings.pgpSignPublicKeyId == "0" ? "Encrypt" : "Sign & Encrypt";
    new import_obsidian2.Setting(contentEl).setDesc(signNote).addButton((btn) => btn.setButtonText(buttonName).setCta().onClick(async () => {
      btn.setIcon("loader");
      btn.setDisabled(true);
      await this.EncryptText();
      btn.setDisabled(false);
      btn.setButtonText(buttonName);
    }));
  }
  // OnClose Method
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  // Method that run when toogle OnChange event is called
  toogleOnChange(value, keyID) {
    if (value) {
      this.listPublicKeyToEncrypt.push(keyID);
    } else {
      this.listPublicKeyToEncrypt.remove(keyID);
    }
  }
  // Method to encript text with previous configuration
  async EncryptText() {
    if (this.encryptMode == "Inline" /* INLINE */) {
      let encryptedTextResult = await gpgEncrypt(this.plugin.settings, this.editor.getSelection(), this.listPublicKeyToEncrypt, this.plugin.settings.pgpSignPublicKeyId);
      if (encryptedTextResult.error) {
        new import_obsidian2.Notice(encryptedTextResult.error.message);
      } else {
        this.editor.replaceSelection(this.BufferToSecretBase64(encryptedTextResult.result));
        this.close();
      }
    } else if (this.encryptMode == "Document" /* DOCUMENT */) {
      let encryptedTextResult = await gpgEncrypt(this.plugin.settings, this.editor.getValue(), this.listPublicKeyToEncrypt, this.plugin.settings.pgpSignPublicKeyId);
      if (encryptedTextResult.result) {
        this.editor.setValue(this.BufferToSecretBase64(encryptedTextResult.result));
        this.close();
      } else if (encryptedTextResult.error) {
        new import_obsidian2.Notice(encryptedTextResult.error.message);
      }
    }
  }
  // Convert Buffer to text in Base64 with some scape characters to be identify in LivePreview
  BufferToSecretBase64(bufferEncrypted) {
    return "`" + GPG_INLINE_ENCRYPT_PREFIX + " " + bufferEncrypted.toString("base64") + "`";
  }
};

// src/HotKeys.ts
var HotKeys = class {
  // Constructor with App and GpgEncryptPlugin
  constructor(app, plugin) {
    // HotKey to Encrypt Inline
    this.GpgEncryptInline = {
      id: "inline",
      name: "Encrypt inline",
      icon: "lock",
      editorCallback: (editor, view) => {
        new EncryptModal(this.app, this.plugin, "Inline" /* INLINE */, editor, view).open();
      }
    };
    // HotKey to Encrypt Document
    this.GpgEncryptDocument = {
      id: "document",
      name: "Encrypt document",
      icon: "lock",
      editorCallback: (editor, view) => {
        new EncryptModal(this.app, this.plugin, "Document" /* DOCUMENT */, editor, view).open();
      }
    };
    this.app = app;
    this.plugin = plugin;
  }
};

// main.ts
var import_obsidian6 = require("obsidian");

// src/LivePreview.ts
var import_view = require("@codemirror/view");
var import_obsidian5 = require("obsidian");
var import_state = require("@codemirror/state");

// src/DecryptPreviewModal.ts
var import_obsidian4 = require("obsidian");

// src/DecryptModal.ts
var import_obsidian3 = require("obsidian");
var DecryptModal = class extends import_obsidian3.Modal {
  // Constructor of modal encrypt
  constructor(app, plainText, extraInfo, plugin, from, to) {
    super(app);
    this.plainText = plainText;
    this.extraInfo = extraInfo;
    this.plugin = plugin;
    this.from = from;
    this.to = to;
  }
  // OnOpen Method
  async onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "Decrypted text" });
    if (this.extraInfo && this.extraInfo.trim() != "") {
      let extraInfoDiv = contentEl.createEl("div");
      extraInfoDiv.className = "gpg-code-sign-ok";
      this.organizeOutText(this.extraInfo, extraInfoDiv);
    }
    contentEl.createEl("p").setText("Plain text preview of the decrypted message:");
    let textArea = contentEl.createEl("textarea");
    textArea.readOnly = true;
    textArea.setText(this.plainText);
    textArea.className = "gpg-plain-text-area";
    let buttons = new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Copy Plain Text").onClick(async () => {
      navigator.clipboard.writeText(this.plainText);
      new import_obsidian3.Notice("Plain text was copied!");
    }));
    if (this.app.workspace.activeEditor && this.app.workspace.activeEditor.editor) {
      buttons.addButton((btn) => btn.setButtonText("Restore plain text to document").setCta().onClick(async () => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (activeView && activeView.getMode() === "preview") {
          new import_obsidian3.Notice("Cannot restore plain text in reading mode. Please switch to Live Preview mode to restore the text.");
          return;
        }
        if (this.app.workspace.activeEditor && this.app.workspace.activeEditor.editor) {
          this.replaceEncryptedTextWithPlainText(this.from, this.to, this.app.workspace.activeEditor.editor);
        } else {
          new import_obsidian3.Notice("Error restoring plain text: activeEditor or editor are not available");
        }
        this.close();
      }));
    }
  }
  // Function to replace the encrypted with plaintext
  replaceEncryptedTextWithPlainText(from, to, editor) {
    const fullText = editor.getValue();
    const encryptedText = fullText.substring(from, to);
    const lines = editor.getValue().split("\n");
    let charCount = 0;
    for (let lineNum = 0; lineNum < lines.length; lineNum++) {
      const line = lines[lineNum];
      const lineStart = charCount;
      const lineEnd = charCount + line.length;
      if (lineStart <= from && lineEnd >= to) {
        const chFrom = from - lineStart;
        const chTo = to - lineStart;
        const editorPositionFrom = { ch: chFrom, line: lineNum };
        const editorPositionTo = { ch: chTo, line: lineNum };
        editor.replaceRange(this.plainText, editorPositionFrom, editorPositionTo);
        new import_obsidian3.Notice("Plain text restored successfully!");
        return;
      }
      charCount += line.length + 1;
    }
    const pattern = new RegExp("`" + encryptedText.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "`", "g");
    const fullTextWithPattern = editor.getValue();
    if (pattern.test(fullTextWithPattern)) {
      const newText = fullTextWithPattern.replace(pattern, this.plainText);
      editor.setValue(newText);
      new import_obsidian3.Notice("Plain text restored successfully!");
      return;
    }
    new import_obsidian3.Notice("The encrypted text was not found in the current document");
  }
  // Organize out text into code elements
  organizeOutText(outText, divCode) {
    let isFirstLine = true;
    let lines = outText.split("\n");
    lines.forEach((line) => {
      if (!isFirstLine) {
        divCode.createEl("br");
      }
      divCode.createEl("code").setText(line);
      isFirstLine = false;
    });
  }
  // OnClose Method
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/DecryptPreviewModal.ts
var DecryptPreviewModal = class extends import_obsidian4.Modal {
  // Constructor of modal encrypt
  constructor(app, encryptedMessageBase64, plugin, from, to) {
    super(app);
    this.plugin = plugin;
    this.from = from;
    this.to = to;
    let encryptedMessageBase64WithoutScapeKeys = encryptedMessageBase64.substring(GPG_INLINE_ENCRYPT_PREFIX.length + 1, encryptedMessageBase64.length);
    this.encryptedMessageBase64 = encryptedMessageBase64WithoutScapeKeys;
    let bufferObj = Buffer.from(encryptedMessageBase64WithoutScapeKeys, "base64");
    this.encryptedMessage = bufferObj.toString("utf8");
  }
  // OnOpen Method
  async onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", { text: "Decrypt Preview" });
    contentEl.createEl("p").setText("Preview encrypted text:");
    const divCode = contentEl.createEl("div");
    divCode.className = "gpg-code-preview";
    let encryptedMessageSplited = this.encryptedMessage.split("\n");
    const max_number_rows = 20;
    let isMiddleDotsPrinted = false;
    for (let i = 0; i < encryptedMessageSplited.length; i++) {
      let encryptedMessageLine = encryptedMessageSplited[i];
      if (encryptedMessageSplited.length > max_number_rows) {
        if (i >= max_number_rows / 2 && i < encryptedMessageSplited.length - max_number_rows / 2 - 1) {
          if (isMiddleDotsPrinted) {
            continue;
          } else {
            isMiddleDotsPrinted = true;
            encryptedMessageLine = ". . .";
          }
        }
      }
      divCode.createEl("code").setText(this.standarizeLinePreview(encryptedMessageLine));
      divCode.createEl("br");
    }
    let buttonName = "Decrypt";
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText("Copy encrypted text").onClick(async () => {
      navigator.clipboard.writeText(this.encryptedMessage);
      new import_obsidian4.Notice("Encrypted text was copied!");
    })).addButton((btn) => btn.setButtonText(buttonName).setCta().onClick(async () => {
      btn.setIcon("loader");
      btn.setDisabled(true);
      let decryptedTextResult = await gpgDecrypt(this.plugin.settings, this.encryptedMessage);
      if (decryptedTextResult.result) {
        let extraInfo = "";
        if (decryptedTextResult.error) {
          extraInfo = decryptedTextResult.error.message;
        }
        new DecryptModal(this.app, decryptedTextResult.result.toString().trim(), extraInfo, this.plugin, this.from, this.to).open();
        this.close();
      } else if (decryptedTextResult.error) {
        new import_obsidian4.Notice(decryptedTextResult.error.message);
      }
      btn.setDisabled(false);
      btn.setButtonText(buttonName);
    }));
  }
  // OnClose Method
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  // Function to stadarize a line in preview screen
  standarizeLinePreview(line) {
    line = line.trim();
    if (line && line.length > 0) {
      return line.substring(0, line.length > 40 ? 40 : line.length) + (line.length > 40 ? "..." : "");
    }
    return "";
  }
};

// src/LivePreview.ts
var EncryptedWidget = class extends import_view.WidgetType {
  // Constructor function with initial args
  constructor(app, value, plugin, from, to) {
    super();
    this.app = app;
    this.value = value;
    this.plugin = plugin;
    this.from = from;
    this.to = to;
  }
  // Method that will manipulate DOM to include decrypt button
  toDOM() {
    const div = document.createElement("span");
    div.addClass("gpg-decrypt-div");
    let a = div.createEl("a");
    a.addClass("gpg-decrypt-a");
    a.onClickEvent(() => {
      new DecryptPreviewModal(this.app, this.value, this.plugin, this.from, this.to).open();
    });
    return div;
  }
};
var livePreviewExtensionGpgEncrypt = (app, plugin) => import_view.ViewPlugin.fromClass(
  class {
    // Constructor to inicialize EditorView
    constructor(view) {
      this.decorations = this.buildDecorations(view);
    }
    // Update function
    update(update) {
      if (!update.state.field(import_obsidian5.editorLivePreviewField)) {
        this.decorations = import_view.Decoration.none;
        return;
      }
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = this.buildDecorations(update.view);
      }
    }
    // Function to build decorations
    buildDecorations(view) {
      if (!view.state.field(import_obsidian5.editorLivePreviewField)) {
        return import_view.Decoration.none;
      }
      const builder = new import_state.RangeSetBuilder();
      for (const { from, to } of view.visibleRanges) {
        const text = view.state.doc.sliceString(from, to);
        const codePattern = /`(gpg-base-64[^`]+)`/g;
        let match;
        while ((match = codePattern.exec(text)) !== null) {
          const matchStart = from + match.index;
          const matchEnd = matchStart + match[0].length;
          const encryptedValue = match[1];
          builder.add(
            matchStart,
            matchEnd,
            import_view.Decoration.replace({
              widget: new EncryptedWidget(app, encryptedValue, plugin, matchStart, matchEnd)
            })
          );
        }
      }
      return builder.finish();
    }
    // Destry method
    destroy() {
    }
  },
  { decorations: (instance) => instance.decorations }
);

// src/ReadingModeProcessor.ts
var registerReadingModeProcessor = (app, plugin) => {
  return (el, ctx) => {
    const codeElements = el.querySelectorAll("code");
    codeElements.forEach((codeEl) => {
      const text = codeEl.textContent || "";
      if (text.startsWith(GPG_INLINE_ENCRYPT_PREFIX)) {
        const wrapper = document.createElement("span");
        wrapper.addClass("gpg-decrypt-div");
        const decryptButton = document.createElement("a");
        decryptButton.addClass("gpg-decrypt-a");
        decryptButton.addEventListener("click", async () => {
          let matchStart = 0;
          let matchEnd = 0;
          const file = app.workspace.getActiveFile();
          if (file) {
            const content = await app.vault.read(file);
            const pattern = new RegExp(`\`${text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\``);
            const match = pattern.exec(content);
            if (match && match.index !== void 0) {
              matchStart = match.index;
              matchEnd = matchStart + match[0].length;
            }
          }
          new DecryptPreviewModal(app, text, plugin, matchStart, matchEnd).open();
        });
        wrapper.appendChild(decryptButton);
        codeEl.replaceWith(wrapper);
      }
    });
  };
};

// main.ts
var GpgEncryptPlugin = class extends import_obsidian6.Plugin {
  // OnLoad Method in PGP Encrypt Plugin
  async onload() {
    await new Settings(this).loadSettings();
    this.addSettingTab(new GpgSettingsTab(this.app, this));
    let hotKeys = new HotKeys(this.app, this);
    this.addCommand(hotKeys.GpgEncryptInline);
    this.addCommand(hotKeys.GpgEncryptDocument);
    this.registerEditorExtension(livePreviewExtensionGpgEncrypt(this.app, this));
    this.registerMarkdownPostProcessor(registerReadingModeProcessor(this.app, this));
  }
  // OnUnload Method in PGP Encrypt Plugin
  onunload() {
  }
};

/* nosourcemap */